//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuikDB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuikDB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Data.
        /// </summary>
        public static string DATARESTORE_ADDL_DATA_HEADER {
            get {
                return ResourceManager.GetString("DATARESTORE_ADDL_DATA_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string DATARESTORE_BROWSE_BUTTON {
            get {
                return ResourceManager.GetString("DATARESTORE_BROWSE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Database.
        /// </summary>
        public static string DATARESTORE_CURRENT_DATABASE_HEADER {
            get {
                return ResourceManager.GetString("DATARESTORE_CURRENT_DATABASE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Backup Location.
        /// </summary>
        public static string DATARESTORE_DB_HINT {
            get {
                return ResourceManager.GetString("DATARESTORE_DB_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Restore.
        /// </summary>
        public static string DATARESTORE_DBRESTORE_HEADER {
            get {
                return ResourceManager.GetString("DATARESTORE_DBRESTORE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Info.
        /// </summary>
        public static string DATARESTORE_EXPANDER_HEADER {
            get {
                return ResourceManager.GetString("DATARESTORE_EXPANDER_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Restore.
        /// </summary>
        public static string DATARESTORE_POSTRESTORE_HEADER {
            get {
                return ResourceManager.GetString("DATARESTORE_POSTRESTORE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Restore.
        /// </summary>
        public static string DATARESTORE_PRERESTORE_HEADER {
            get {
                return ResourceManager.GetString("DATARESTORE_PRERESTORE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string DATARESTORE_RESET_BUTTON {
            get {
                return ResourceManager.GetString("DATARESTORE_RESET_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Restore.
        /// </summary>
        public static string DATARESTORE_START_BUTTON {
            get {
                return ResourceManager.GetString("DATARESTORE_START_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Logs.
        /// </summary>
        public static string DATARESTORE_TXN_LOGS_HEADER {
            get {
                return ResourceManager.GetString("DATARESTORE_TXN_LOGS_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string HOME_CHECK_FOR_UPDATE {
            get {
                return ResourceManager.GetString("HOME_CHECK_FOR_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit QuikDB.
        /// </summary>
        public static string LOGIN_EXIT_TOOLTIP {
            get {
                return ResourceManager.GetString("LOGIN_EXIT_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LOGIN_MAINLOGINBUTTON_LABEL {
            get {
                return ResourceManager.GetString("LOGIN_MAINLOGINBUTTON_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LOGIN_PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("LOGIN_PASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Management Utility.
        /// </summary>
        public static string LOGIN_SUBHEADER_LABEL {
            get {
                return ResourceManager.GetString("LOGIN_SUBHEADER_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LOGIN_USERNAME_LABEL {
            get {
                return ResourceManager.GetString("LOGIN_USERNAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Database.
        /// </summary>
        public static string RECOVERY_BACKUP_DATABASE {
            get {
                return ResourceManager.GetString("RECOVERY_BACKUP_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency Check.
        /// </summary>
        public static string RECOVERY_CONSISTENCY_CHECK {
            get {
                return ResourceManager.GetString("RECOVERY_CONSISTENCY_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Database.
        /// </summary>
        public static string RECOVERY_NEW_DATABASE {
            get {
                return ResourceManager.GetString("RECOVERY_NEW_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Database.
        /// </summary>
        public static string RECOVERY_RESTORE_DATABASE {
            get {
                return ResourceManager.GetString("RECOVERY_RESTORE_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking App Prerequisites.
        /// </summary>
        public static string SPLASH_CHECK_PREREQUISITES {
            get {
                return ResourceManager.GetString("SPLASH_CHECK_PREREQUISITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Initial Directories..
        /// </summary>
        public static string SPLASH_INITIALIZE_DIRECTORIES {
            get {
                return ResourceManager.GetString("SPLASH_INITIALIZE_DIRECTORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Utilities.
        /// </summary>
        public static string TOOLS_DRIVE_UTILITIES {
            get {
                return ResourceManager.GetString("TOOLS_DRIVE_UTILITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string TOOLS_LOGS {
            get {
                return ResourceManager.GetString("TOOLS_LOGS", resourceCulture);
            }
        }
    }
}
